# Arabic titles keyed by exact English string from UmmahAPI.
AR_BY_EN: dict[str, str] = {
    "After Eating": "بعد الأكل",
    "After Rain": "بعد المطر",
    "After Wudu": "بعد الوضوء",
    "Al-Fatiha (Opening Chapter)": "الفاتحة (افتتاح القرآن)",
    "Alhamdulillah After Prayer": "الحمد لله بعد الصلاة",
    "Allahu Akbar After Prayer": "الله أكبر بعد الصلاة",
    "Ayat al-Kursi After Prayer": "آية الكرسي بعد الصلاة",
    "Before Eating": "قبل الأكل",
    "Before Reciting the Quran": "قبل تلاوة القرآن",
    "Before Sleeping": "قبل النوم",
    "Before Wudu": "قبل الوضوء",
    "Between Sujud (Prostrations)": "بين السجدتين",
    "Complete After-Wudu Dua": "دعاء الوضوء الكامل",
    "Complete Tasbih, Tahmid, Takbir": "التسبيح والتحميد والتكبير",
    "Comprehensive Forgiveness": "الاستغفار الشامل",
    "Dua After Adhan": "دعاء بعد الأذان",
    "Dua Before Intercourse": "دعاء قبل الجماع",
    "Dua Before Salam (After Tashahud)": "دعاء قبل السلام",
    "Dua Between Adhan and Iqamah": "دعاء بين الأذان والإقامة",
    "Dua Upon Completing the Quran": "دعاء عند ختم القرآن",
    "Dua Upon Seeing a Newborn": "دعاء عند رؤية المولود",
    "Dua When Invited to Eat": "دعاء عند دعوة الطعام",
    "Dua While Waiting for Prayer": "دعاء انتظار الصلاة",
    "Dua at Arafah": "دعاء يوم عرفة",
    "Dua at Iftar": "دعاء عند الإفطار",
    "Dua at Safa and Marwa": "دعاء عند الصفا والمروة",
    "Dua at Tahajjud": "دعاء التهجد",
    "Dua at a Wedding": "دعاء في العرس",
    "Dua at the Beginning of a Journey": "دعاء بداية السفر",
    "Dua at the Graveside": "دعاء عند القبر",
    "Dua at the Ka'bah (Seeing the Ka'bah)": "دعاء عند رؤية الكعبة",
    "Dua at the Market": "دعاء عند السوق",
    "Dua for Barakah in Wealth": "دعاء البركة في المال",
    "Dua for Beneficial Knowledge": "دعاء العلم النافع",
    "Dua for Best of This World and Next": "دعاء خير الدنيا والآخرة",
    "Dua for Deceased Parents": "دعاء للوالدين المتوفين",
    "Dua for Distress": "دعاء الكرب",
    "Dua for Ease in Difficulty": "دعاء الفرج",
    "Dua for Good Character": "دعاء حسن الخلق",
    "Dua for Good Morning": "دعاء صباح الخير",
    "Dua for Healing": "دعاء الشفاء",
    "Dua for Laylat al-Qadr": "دعاء ليلة القدر",
    "Dua for Living Parents' Well-being": "دعاء لصلاح الوالدين",
    "Dua for Newborn Protection": "دعاء حماية المولود",
    "Dua for Pain in the Body": "دعاء ألم الجسد",
    "Dua for Parents": "دعاء للوالدين",
    "Dua for Patience in Grief": "دعاء الصبر عند الحزن",
    "Dua for Paying Off Debt": "دعاء قضاء الدين",
    "Dua for Provision (Rizq)": "دعاء الرزق",
    "Dua for Righteous Children": "دعاء صلاح الذرية",
    "Dua for Someone Who Is Ill": "دعاء للمريض",
    "Dua for Steadfastness on the Truth": "دعاء الثبات على الحق",
    "Dua for a Bad Dream": "دعاء الرؤيا السيئة",
    "Dua for a Righteous Spouse and Offspring": "دعاء الزوج الصالح والذرية",
    "Dua for the Deceased": "دعاء للميت",
    "Dua for the Host": "دعاء للمضيف",
    "Dua for the Traveler (From Family at Home)": "دعاء للمسافر",
    "Dua in Ruku": "دعاء الركوع",
    "Dua in Sujud": "دعاء السجود",
    "Dua of Adam and Hawwa": "دعاء آدم وحواء",
    "Dua of Prophet Ayyub (Job)": "دعاء أيوب عليه السلام",
    "Dua of Prophet Ibrahim for His Offspring": "دعاء إبراهيم لذريته",
    "Dua of Prophet Sulayman for Gratitude": "دعاء سليمان للشكر",
    "Dua of Yunus (Jonah)": "دعاء يونس",
    "Dua on Seeing Spouse": "دعاء عند رؤية الزوج",
    "During Thunder": "عند الرعد",
    "Entering a Town or City": "دخول البلدة",
    "Entering the Home": "دخول المنزل",
    "Entering the Masjid": "دخول المسجد",
    "Evening Protection": "حماية المساء",
    "Evening Remembrance": "ذكر المساء",
    "Evening Remembrance of Allah": "ذكر الله في المساء",
    "Evening Seeking Forgiveness": "استغفار المساء",
    "Forgetting Bismillah Before Eating": "نسيان البسملة قبل الأكل",
    "General Protection": "حماية عامة",
    "Hasbiyallah": "حسبي الله",
    "Hasbunallah": "حسبنا الله",
    "Increase in Knowledge": "زيادة العلم",
    "Inna Lillahi (Upon a Calamity)": "إنا لله وإنا إليه راجعون",
    "Istighfar After Prayer": "استغفار بعد الصلاة",
    "Istikhara (Seeking Guidance)": "الاستخارة",
    "La Hawla Wa La Quwwata": "لا حول ولا قوة إلا بالله",
    "La ilaha illallah 10 Times After Fajr and Maghrib": "لا إله إلا الله بعد الفجر والمغرب",
    "Last Two Verses of Surah al-Baqarah": "خاتمة البقرة",
    "Leaving the Home": "الخروج من المنزل",
    "Leaving the Masjid": "الخروج من المسجد",
    "Master of Forgiveness (Sayyid al-Istighfar)": "سيد الاستغفار",
    "Morning Protection with Al-Mu'awwidhat": "حماية الصباح بالمعوذات",
    "Morning Remembrance": "ذكر الصباح",
    "Morning Tasbih": "تسبيح الصباح",
    "Opening Supplication in Prayer": "دعاء استفتاح الصلاة",
    "Opening of Tahajjud Prayer": "افتتاح قيام الليل",
    "Praising Allah Upon Receiving a Blessing": "الحمد عند النعمة",
    "Protection Morning Dua": "دعاء حماية الصباح",
    "Protection from Dajjal": "الاستعاذة من الدجال",
    "Reciting Al-Mu'awwidhat Before Sleep": "المعوذات قبل النوم",
    "Returning From Travel": "العودة من السفر",
    "Rising from Ruku": "الرفع من الركوع",
    "Ruqyah: Bismillah x3, A'udhu x7": "الرقية: بسم الله ومعوذات",
    "Salawat (Ibrahimiyya) in Prayer": "الصلاة الإبراهيمية",
    "Salawat on the Prophet": "الصلاة على النبي",
    "Seeking Forgiveness": "طلب المغفرة",
    "Seeking Protection from Evil Eye": "الاستعاذة من العين",
    "Seeking Refuge After Prayer": "الاستعاذة بعد الصلاة",
    "Seeking Refuge from Useless Knowledge": "الاستعاذة من علم لا ينفع",
    "Stopping at a Place": "النزول في منزل",
    "SubhanAllah After Prayer": "سبحان الله بعد الصلاة",
    "SubhanAllah al-Adheem Morning": "سبحان الله العظيم (صباحًا)",
    "SubhanAllah wa Bihamdihi x100": "سبحان الله وبحمده مائة مرة",
    "SubhanAllahil Adheem wa Bihamdihi": "سبحان الله العظيم وبحمده",
    "Talbiyah": "التلبية",
    "Tashahud": "التشهد",
    "Thanking Allah": "شكر الله",
    "The Best Dhikr": "أفضل الذكر",
    "Travel Dua": "دعاء السفر",
    "Upon Seeing a Good Dream": "عند الرؤيا الحسنة",
    "Upon Waking Up": "عند الاستيقاظ",
    "Upon Waking at Night": "عند اليقظة ليلًا",
    "Visiting the Sick": "عيادة المريض",
    "When Anxious or Worried": "عند الهم والغم",
    "When It Rains": "عند المطر",
    "When Putting On Clothes": "عند لبس الثوب",
    "When Undressing": "عند خلع الثوب",
    "Witr Qunut": "دعاء قنوت الوتر",
}
